services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: odoo-spotlight
    depends_on:
      - db
    ports:
      - "8080:8069"
      - "5681:5678"
    volumes:
      - .env:/etc/odoo/.env
      - ./filestore:/var/lib/odoo/filestore/
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons

  db:
    container_name: odoo_db
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5454:5432"
